wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-rc-7/apache-maven-4.0.0-rc-7-bin.zip
distributionSha256Sum=6ef648cbd5d06c4669fb43256b2fd03954019d97ab4f42fdfaa0a2d46ede9f2e
